### ISSUE TITLE
set up routes for all pages

### ISSUE THREAD

**Issue by Idadelveloper** [WTMBamenda/wtm-bamenda-website-frontend#10]

**Comment by parth656** [comment]
@Idadelveloper @WTMBamenda @Fienne @nangahamandine i set up all your routes for each page kindly assign it to me

**Comment by PetraAG** [comment]
Done @parth656

**Comment by parth656** [comment]
@Idadelveloper @PetraAG @Fienne @nangahamandine  kindly add the hacktober badge to it so that i can get the badge in hacktober
