### ISSUE TITLE
Create the website navigation bar

### ISSUE THREAD

**Issue by Idadelveloper** [WTMBamenda/wtm-bamenda-website-frontend#2]
There is currently no way to easily navigate across pages of the website. it will be important to have a navigation bar where users can easily navigate cross different pages

Create navbar as shown [here](https://www.figma.com/file/FHiXmUWupq9y5M5Um0BFKq/UI?type=design&node-id=0-1&mode=design&t=BQBNxQuh7wkIVdEy-0)

**Comment by Ndzedzenyuy** [comment]
@Idadelveloper please i will love to work on the navigation issue

**Comment by Ndzedzenyuy** [comment]
@PetraAG  please i will love to contribute to this issue?

**Comment by Idadelveloper** [comment]
@Ndzedzenyuy you can start working on it
