### ISSUE TITLE
Create Project Details page

### ISSUE THREAD

**Issue by PetraAG** [WTMBamenda/wtm-bamenda-website-frontend#28]
Create the Project details page as seen in the [Figma design](https://www.figma.com/file/FHiXmUWupq9y5M5Um0BFKq/UI?type=design&node-id=122-389&mode=design&t=DguuH9eufiC4J3YQ-0).

With the help of already created components such as 

- Top Navigation,
-  Bottom Navigation bar, 

seen in closed issues [here](https://github.com/WTMBamenda/wtm-bamenda-website-frontend/pulls?q=is%3Apr+is%3Aclosed), create the Project details page.

**Comment by shenyuygoodness** [comment]
@PetraAG   I wish to work on this page
