### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by Idadelveloper** [WTMBamenda/wtm-bamenda-website-frontend#3]
There is currently no homepage in the project. We need a home/landing page for the site visitors.

[Design](https://www.figma.com/file/FHiXmUWupq9y5M5Um0BFKq/UI?type=design&node-id=0-1&mode=design&t=BQBNxQuh7wkIVdEy-0)

**Comment by Fenui-codes** [comment]
Interested

**Comment by Fenui-codes** [comment]
Interested

**Comment by Idadelveloper** [comment]
@Fenui-codes you can start working. However you may need certain components like the navbar and bottom navigation. You can still go ahead and work on it while others are working on the components to make the landing page complete

**Comment by uzeking6** [comment]
hello @Fenui-codes can i work with you? please if possible
