### ISSUE TITLE
Update project readme

### ISSUE THREAD

**Issue by Idadelveloper** [WTMBamenda/wtm-bamenda-website-frontend#4]
**Problem**: There are no detailed instructions on the readme.md file. Hence when new contributors visit the repo, they may have a hard time getting started with contributing.

The current readme.md file is basically empty. It needs to to be updated to contain a description of the project, project requirements to be installed and steps to run the code locally.

Skills required: Technical writing, knowledge of setting up a React project

**Comment by pragyapranati** [comment]
As a seasoned technical writer I am interested in contributing to this project. Where can I get the details of the project?

**Comment by PetraAG** [comment]
@pragyapranati , Check the guidelines for the figma project file, and if you have further questions, please get to me on whatsapp. I have assigned you to this issue

**Comment by pragyapranati** [comment]
@PetraAG , Can you please share the link of figma project file

**Comment by manfomaiva** [comment]
@PetraAG, please I'll like to join @pragyapranati to work on this issue
