### ISSUE TITLE
Create carousel for sponsors and partners

### ISSUE THREAD

**Issue by Idadelveloper** [WTMBamenda/wtm-bamenda-website-frontend#5]
A single carousel component should be created that can be populated with the various partners and sponsors.

Skills: React, HTML, CSS

**Comment by kinyuykelly** [comment]
@Idadelveloper  and @PetraAG  i would love to work on this

**Comment by Idadelveloper** [comment]
@Kinyuykelly you can start working on it

**Comment by kinyuykelly** [comment]
okay
