### ISSUE TITLE
Create bottom navigation bar

### ISSUE THREAD

**Issue by Idadelveloper** [WTMBamenda/wtm-bamenda-website-frontend#6]
As per the [design](https://www.figma.com/file/FHiXmUWupq9y5M5Um0BFKq/UI?type=design&node-id=122-389&mode=design&t=6UrItohE94JPA2Yi-0), there is the need for a bottom navigation bar to be used across all pages

Skills required: React, CSS

**Comment by olgangala2** [comment]
@Idadelveloper i wish to work on this.

**Comment by Idadelveloper** [comment]
@olgangala2 you can start working
