### ISSUE TITLE
Create card component to display ambassadors and organizers

### ISSUE THREAD

**Issue by Idadelveloper** [WTMBamenda/wtm-bamenda-website-frontend#7]
Refer to the [about page of the design](https://www.figma.com/file/FHiXmUWupq9y5M5Um0BFKq/UI?type=design&node-id=122-389&mode=design&t=6UrItohE94JPA2Yi-0) and create a card that contains:
- Person's image
- Occupation
- Social links

**Comment by shenyuygoodness** [comment]
@Idadelveloper please I wish to work on this issue.

**Comment by Idadelveloper** [comment]
@shenyuygoodness you can start working
