### ISSUE TITLE
Create card for member profile for the about page

### ISSUE THREAD

**Issue by Idadelveloper** [WTMBamenda/wtm-bamenda-website-frontend#8]
As per the [about page of the design](https://www.figma.com/file/FHiXmUWupq9y5M5Um0BFKq/UI?type=design&node-id=122-389&mode=design&t=ZGNDuvcxEoOjTh8V-0), create a card to display:
- Member's photo
- Member's name
- Social links
- etc

**Comment by Dabi-ayu** [comment]
i can take up this issue team lead...

**Comment by Idadelveloper** [comment]
@Dabi-ayu you can start working
