### ISSUE TITLE
Create 'join our community' button

### ISSUE THREAD

**Issue by Idadelveloper** [WTMBamenda/wtm-bamenda-website-frontend#9]
In the design, there's a button in the navigation bar and some pages with a 'join our community' button. Create a button component referencing what you see in the [design](https://www.figma.com/file/FHiXmUWupq9y5M5Um0BFKq/UI?type=design&node-id=122-389&mode=design&t=ZGNDuvcxEoOjTh8V-0)

**Comment by Dudura101** [comment]
I will like to work on this

**Comment by Idadelveloper** [comment]
Issue was tackled in #21 by @Ndzedzenyuy
